### ISSUE TITLE
 Outreach Portal Login : Captcha to be added 

### ISSUE THREAD

**Issue by priya100raman** [vlead/outreach-portal#241] opened 2017-04-04 04:52 UTC
Based on the meeting on 22nd March 2017 : Captcha to be added to Outreach Portal Login

**Comment by madhavipuliraju** [comment] 2019-02-26 06:39
Duplicate of issue: https://github.com/vlead/outreach-portal/issues/227

**Closed by madhavipuliraju** 2019-02-26 06:39 UTC
